### ISSUE TITLE
Division of work

### ISSUE THREAD

**Issue by Shubham-Rasal** [Shubham-Rasal/ExamArchive#3]
- [x] Divide the frontend and backend work
- [x] Define the apis and core features
- [x] work on setup a boilerplat deployment

**Comment by Bismay5467** [comment]
Before dividing the frontend and backend work I want to know what features you guys have thought of.

@VaibhavNITK like we have discussed yesterday I won't be of much help for the website designing part. You need to take care of that.

@Shubham-Rasal I am not sure how things actually work in production. I need a bit of time to understand that before commenting on it. However I've heard that GitHub Actions is highly beneficial for establishing a CI/CD pipeline.

**Comment by VaibhavNITK** [comment]
It's okay, I can do the front-end job.
As for the features, these are a few of the fundamental pages that i can think of:
Landing Page ● Sign up Page ● Register Page ● Home Page ● Profile Page ● Upload Document page

What other features can we incorporate into our project?

**Comment by Bismay5467** [comment]
> What other features can we incorporate into our project?

One of the features that I had mentioned in my proposal was a dedicated page for topic coverage analysis. You may go through my proposal that I had shared with you to get more insights on this feature.

Other than that we would need a dedicated page to search question paper based on certain filters (year, name of examination, etc.) Clicking on any of these filtered question paper would redirect us to a preview page.

You may go through my proposal (the very first section - project objectives and proposed work) to get more insights on all the features I had mentioned.

Let me know what you think of those ideas.

For the upload document page we need to decide if user can upload a single file at a time, or multiple files, or how to take input for the metadata (like name of examination, year, etc. ) associated with those files.

**Comment by Shubham-Rasal** [comment]
## Vaibhav

- [ ] Landing page

The landing page should have a navbar with a single login button. There should be a search button and filters. The fields in the filter can be hardcoded for now. Try to implement the search and filter feature.

## Bismay

To be decided for supabase or MongoDB with Nodejs

**Comment by Shubham-Rasal** [comment]
Nextjs learning resources: 
- https://nextjs.org/learn
